services:
  gcap-statement:
    image: ${REGISTRY}/gcap-statement:${TAG}
    container_name: gcap-statement

    ports:
      - "${SERVER_PORT}:3000"

    environment:
      BASE_URL: ${BASE_URL}
      PRICE_BASE_URL: ${PRICE_BASE_URL}
      